config/routes.rb
Rails.application.routes.draw do


  root :to => "presentation_page#index"
  resources :password_resets
  resources :projects do
    get 'most_favorited', on: :collection
    get 'recent', on: :collection

    resources :users, :controller => "projects/users"
    post :favorite, :to =>"projects/favorites#create"
    delete :favorite, :to =>"projects/favorites#destroy"
    resources :widgets
  end
  #resources :widgets
  resources :forums do
    resources :topics do
      resources :messages
    end
  end



  resources :comments
  resources :projects
  resources :sessions


	get 'auth/:provider/callback', to: 'omni_auth_login#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'omni_auth_login#destroy'
  post "/users/favorite_project/:project_id" => "users#favorite_project"
  post "/users/disfavorite_project/:project_id" => "users#disfavorite_project"
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  
  #adding routes for new user email confirmation: 
  resources :users do

      member do
        get :confirm_email
      end
  end

end

app/controllers/presentation_page_controller.rb
class PresentationPageController < ApplicationController

  # GET /presentation_pages
  def index
  end

  # GET /presentation_pages/1
  def show
  end


  # GET /presentation_pages/1/edit
  def edit
  end


end

app/helpers/presentation_pages_helper.rb
module PresentationPagesHelper
end

app/views/presentation_page/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-mega" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggler hamburger hamburger-close collapsed" data-target="#example-navbar-collapse-3" data-toggle="collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="hamburger-bar"></span>
      </button>
      <a class="navbar-brand" href="javascript:void(0)">FlossCoach</a>
    </div>
    <div class="navbar-collapse collapse" id="example-navbar-collapse-3" aria-expanded="false">

      <% if logged_in? %>
      <%= link_to "FlossCoach Portal", projects_path, class: "mr-20 btn btn-primary navbar-right navbar-btn " %>
      <% else %>
      <%= link_to "Sign Up", new_user_path, class: "mr-20 btn btn-info navbar-right navbar-btn" %>
      <%= link_to "Sign In", sign_in_path, class: "mr-20 btn btn-primary navbar-right navbar-btn " %>
      <% end %>
    </div>
  </div>
</nav>

app/views/presentation_page/index.html.erb
<body class="animsition" >
  <%= render 'navbar' %>

  <div class="page container-fluid " data-animsition-in="fade-in" data-animsition-out="fade-out">
    <div class="row bg-grey-800 text-white">
      <div class="page-content ">
        <span class="icon  float-left"></span>
        <h1 class="text-white font-size-50" >
          <i class="icon md-account-add font-size-70"></i>
          What is it?
          </h1>
          <p class="lead text-left">
            FlossCoach is aimed to help newcomers to Free/Libre Open Source Software (FLOSS)
          </p>
        </div>
      </div>

      <div class="row bg-indigo-500 text-white">
        <div class="page-content ">
          <h1 class="text-white font-size-50" >
            <i class="icon md-eye font-size-70"></i>
              Create or add your project on FlossCoach</h1>
            <p class="lead bg-indigo-500 text-left">
              By <%= link_to "adding your project", new_user_path, style: "color: white; font-weight: bold"%> new developers can contribute to it 
            </p>
            </div>
          </div>


          <div class="row bg-purple-800  text-white">
            <div class="page-content ">
              <h1 class="text-purple-800 font-size-50 text-white">
                <i class="icon md-collection-item font-size-70"></i>
                Currently registered <%= link_to "projects ", projects_path, style: "color: white"%>
              </h1>
              <p class="lead text-center" >
                
                
                  </p>
                <div class="col-md-12 mt-50">
                  <ul class="blocks-6">
                    <% Project.all.each do |project|%>
                    <li class="text-center">
                      <%= link_to project, class:"thumbnail m-0" do %>
                      <%= image_tag project.image.url(:thumb), class:"center-block", width:50%>
                      <% end %>
                      <p><b><%= project.name %></b></p>
                    </li>
                    <% end %>

                  </ul>
                </div>
              </div>
            </div>


          </div>
        </body>