config/routes.rb
Rails.application.routes.draw do


  root :to => "presentation_page#index"
  resources :password_resets
  resources :projects do
    get 'most_favorited', on: :collection
    get 'recent', on: :collection

    resources :users, :controller => "projects/users"
    post :favorite, :to =>"projects/favorites#create"
    delete :favorite, :to =>"projects/favorites#destroy"
    resources :widgets
  end
  #resources :widgets
  resources :forums do
    resources :topics do
      resources :messages
    end
  end



  resources :comments
  resources :projects
  resources :sessions


	get 'auth/:provider/callback', to: 'omni_auth_login#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'omni_auth_login#destroy'
  post "/users/favorite_project/:project_id" => "users#favorite_project"
  post "/users/disfavorite_project/:project_id" => "users#disfavorite_project"
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  
  #adding routes for new user email confirmation: 
  resources :users do

      member do
        get :confirm_email
      end
  end

end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :forum
  has_many :messages
  serialize :tags
  validate :validate_tags
  belongs_to :user
  validates_presence_of :forum
  validates_presence_of :user

  def project
    forum.project
  end

  def messages_count
    messages.count
  end

  def recent?
    created_at > 2.day.ago
  end
  
  #private
  #def validate_tags
    #if tags.length != tags.uniq.length
     # errors.add(:tags, " have repeated elements")
    #end
  #end

  private
  def validate_tags
    
    if !tags.nil? && !tags.empty?
      if tags.length != tags.uniq.length
        errors.add(:tags, " have repeated elements")
      end
    end
    
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :set_forum
  before_action :authorize, except: [:show]


  # GET /topics
  def index
    @topics = @project.topics
  end

  # GET /topics/1
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  def create
    @topic = Topic.new(topic_params)
    @topic.forum = @forum
    @topic.user = current_user
    if @topic.save
      redirect_to @forum.project, notice: 'Topic was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /topics/1
  def update
    if @topic.update(topic_params)
      redirect_to @topic, notice: 'Topic was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /topics/1
  def destroy
    @topic.destroy
    redirect_to @project, notice: 'Topic was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end
    def set_project
      @project = Project.find(params[:project_id])
    end
    def set_forum
      @forum = Forum.find(params[:forum_id])
      @project = @forum.project
    end

    # Only allow a trusted parameter "white list" through.
    def topic_params
      params.require(:topic).permit!
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for [@forum, topic] do |f| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> must be fixed in order to save this topic:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-lg-12 form-group">
      <%= f.text_field :title , :class => "form-control", placeholder: "Topic title" %>
    </div>

    <div class="col-lg-12 form-group">
      <%= f.text_area :content, :class => "form-control", placeholder: "Content" %>
    </div>
</div>
<div class="row">

  <div class="col-lg-12 form-group">
    <%= f.submit %>
  </div>
</div>

<% end %>

app/views/topics/_topic.html.erb
<tr data-href="<%= forum_topic_url(@forum, topic) %>" data-toggle="slidePanel">
  <td class="pre-cell"></td>
  <td class="cell-60 responsive-hide">
    <a class="avatar" href="javascript:void(0)">
      <%= image_tag topic.user.avatar.url(:thumb), class: "img-fluid" %>
    </a>
  </td>
  <td>
    <div class="content">
      <div class="title">
        <%= topic.title %>
        <div class="flags responsive-hide">
          <% if false %>
          <span class="sticky-top badge badge-round badge-danger">
            <i class="icon md-caret-up-circle" aria-hidden="true"></i>
            TOP</span>

            <% end %>
          <% if topic.locked?%>
          <i class="locked icon md-lock"></i>
          <% end %>
        </div>
      </div>
      <div class="metas">
        <span class="author"><%= topic.user.name %></span>
        <span class="started">1 day ago</span>
        <span class="badges">Themes</span>
      </div>
    </div>
  </td>
  <td class="cell-80 forum-posts">
    <span class="num"><%= topic.messages_count %></span>
    <span class="unit">Post</span>
  </td>
  <td class="suf-cell"></td>
</tr>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Topics</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Back', project_path(@forum.project) %>

app/views/topics/show.html.erb
<%= render 'visitor/header' unless current_user %>
<%= render 'visitor/menu' unless current_user %>

<div class="panel">
  <div class="panel-body">
    <div class="comments mx-20">
      <h1><%= @topic.title %></h1>
      <div class="comment media">
        <div class="pr-15">
          <%= link_to @topic.user, class: "avatar avatar-md" do %>
            <%= image_tag @topic.user.avatar.url(:thumb) %>
          <% end %>
        </div>
        <div class="comment-body media-body">
          <div class="comment-title">
            <div class="comment-meta float-right">
              <span>04.07.11, 8:02 AM</span>
            </div>
            <%= link_to @topic.user.name ,@topic.user, class: "comment-author"%>
          </div>
          <div class="comment-content">
            <p>
              <%= @topic.content %>
            </p>

          </div>
          <div class="comment-actions text-left">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>




<%= link_to 'Adicionar nova mensagem', new_forum_topic_message_path(@topic.forum, @topic)%>

<div class="panel">
  <div class="panel-body">
    <div class="comments mx-20">
      <h3>Answers for topic <b><%= @topic.title %></b></h3>

      <% @topic.messages.each do |message| %>


      <div class="comment media">
        <div class="pr-15">
          <%= link_to @topic.user, class: "avatar avatar-md" do %>
          <%= image_tag @topic.user.avatar.url(:thumb) %>
          <% end %>
        </div>
        <div class="comment-body media-body">
          <div class="comment-title">
            <div class="comment-meta float-right">
              <span>04.07.11, 8:02 AM</span>
            </div>
            <%= link_to @topic.user.name ,@topic.user, class: "comment-author"%>

          </div>
          <div class="comment-content">
            <p><%= message.content %></p>
          </div>

        </div>
      </div>
      <%end%>
    </div>
  </div>
</div>