config/routes.rb
Rails.application.routes.draw do


  root :to => "presentation_page#index"
  resources :password_resets
  resources :projects do
    get 'most_favorited', on: :collection
    get 'recent', on: :collection

    resources :users, :controller => "projects/users"
    post :favorite, :to =>"projects/favorites#create"
    delete :favorite, :to =>"projects/favorites#destroy"
    resources :widgets
  end
  #resources :widgets
  resources :forums do
    resources :topics do
      resources :messages
    end
  end



  resources :comments
  resources :projects
  resources :sessions


	get 'auth/:provider/callback', to: 'omni_auth_login#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'omni_auth_login#destroy'
  post "/users/favorite_project/:project_id" => "users#favorite_project"
  post "/users/disfavorite_project/:project_id" => "users#disfavorite_project"
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  
  #adding routes for new user email confirmation: 
  resources :users do

      member do
        get :confirm_email
      end
  end

end

app/models/project.rb
class Project < ApplicationRecord
  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :description

  belongs_to :user
  has_many :widgets, :dependent => :destroy
  has_and_belongs_to_many :owners, class_name: 'User'
  has_one :forum
 
  has_many :favoriter_projects
  has_many :fans, through: :favoriter_projects, :source => :user
  has_many :comments, through: :widgets
  #mount_uploader :avatar, AvatarUploader
  
  scope :order_by_fans_count, -> {
  joins(:fans).select('projects.*, COUNT(user_id) as user_count').group('projects.id').order('user_count DESC')
  }
  #PaperClip related code:
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates :image, file_size: { less_than: 3.megabytes }
  serialize :tags unless Rails.env.production?

  def get_open_hub_data
    ohp = OpenHubProject.find_by_name(self.name)
    self.description = ohp.description
    self.open_hub_image_url = ohp.logo_url
    self.use_open_hub_data = true
    self.use_open_hub_image = true
    self.tags = ohp.tags
    widget = self.widgets.where(title: "About the project").first
    widget.content = ohp.iframe_html
    widget.save

    widget = self.widgets.where(title: "Resources avaiable").first
    widget.content = ohp.links_html
    widget.save

    widget = self.widgets.where(title: "Technical skills required").first
    widget.content = ohp.iframe_languages_html
    widget.save

  end
  def recent?
    created_at > 2.day.ago
  end

  def owner?(user)
    self.owners.include?(user)
  end

  def self.search(search)
    if search
      where("name LIKE ? OR description LIKE ? OR cast(tags as text) LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      all
    end
  end
end

app/controllers/projects/favorites_controller.rb
class Projects::FavoritesController < ProjectsController

  before_action :set_user
  before_action :set_project

  # POST /users
  def create
    @projects = Project.all
    project = Project.find_by_id(params[:project_id])
    respond_to do |format|
      @user.favorite_project(project)
      if @user.save
        format.js
        format.html{
          flash.now[:notice] = "Project #{@project.name} has been favorited!."
          redirect_to project_path(@project)
        }
      else
        format.js
        format.html{
          flash.now[:notice] = "Erron on favorite project #{@project.name}."
          redirect_to project_path(@project)
        }
      end
    end
  end

  # DELETE /users/1
  def destroy
    @projects = Project.all

    respond_to do |format|
      if @user.favorited_projects.delete(@project)
        format.js
        format.html{
          flash.now[:notice] = "Project #{@project.name} has been disfavorited!."
          redirect_to project_path(@project)
        }
      else
        format.js
        format.html{
          flash.now[:notice] = "Erron on disfavorite project #{@project.name}."
          redirect_to project_path(@project)
        }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = current_user
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

end

app/controllers/projects/users_controller.rb
class Projects::UsersController < ProjectsController

  before_action :set_user, only: [:show, :update, :destroy]
  skip_before_filter :verify_authenticity_token, only: [:update]
  before_action :authorize

  # GET /users
  def index
    @project = Project.all.find(params[:project_id])
  end

  # GET /users/1
  def show
    redirect_to project_users_path, notice: 'Done.'
  end

  # GET /users/new
  def new
    @project = Project.all.find(params[:project_id])
  end

  # GET /users/1/edit
  def edit

  end

  # POST /users
  def create
    @project = Project.all.find(params[:project_id])
    @user = User.find_by_email(params[:email])
    if @user
      @project.owners << @user
      redirect_to project_users_path
    else
      flash.now[:error] = "No user matches with this e-mail."
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update_attributes(user_params)
      respond_to do |format|
        format.json { render :json => { :status => 'Ok', :message => 'Received'}, :status => 200 }
      end
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @project = Project.all.find(params[:project_id])
    @user = @project.owners.find(params[:id])
    if @project.owners.delete(@user)
      redirect_to project_users_path, notice: 'Done.'
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = current_user
  end

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit!
  end

  def set_project
    @project = Project.all.find(params[:project_id])
      #@project = current_user.projects.find(params[:id])
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  respond_to :html, :js, :json
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, only: [:update]
  before_action :authorize, except: [:index, :show]

  # GET /projects
  def index
    @projects = Project.search(params[:search])
 	  @project = Project.new
    @order_by ||= "Recents"
  end

  # GET /projects/1
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end
  
  def recent
    @projects = Project.search(params[:search])
    @project = Project.new
    @order_by = "Recents"

    render :index
  end

  def most_favorited
    @projects = Project.all.search(params[:search])
    @project = Project.new
    @order_by ||= "Most favorited"

    render :index

  end
  # GET /projects/1/edit
  def edit
    unless @project.owner?(current_user)
      render :show, status: :unauthorized, notice: 'Access unauthorized'
    end
    @codigourl = params[:id]
  end

  # POST /projects
  def create
    @project = Project.new(project_params)
    
    @project.widgets << Widget.defaults
    @project.owners << current_user
    #@project.tags = @project.tags.split(",")
    if !@project.tags.nil?
      @project.tags = @project.tags.split(" ").join(",")
    end

    if @project.save
      @project.get_open_hub_data if params[:openhub_check]
      @project.save
      redirect_to @project, notice: t('Your project was successfully added to Flosscoach')
    else
      #@project.tags = @project.tags.join(",")
      flash.now[:notice] = @project.widgets.first.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /projects/1
  # TODO: Refactor
  def update
    if @project.owner?(current_user)
      if @project.update_attributes(project_params)
        respond_to do |format|
          format.html { render :edit, status: :ok, notice: 'Project was successfully updated.'}
          format.json { render :json => { :status => 'Ok', :message => 'Received'}, :status => :ok }
        end
      else
        respond_to do |format|
          format.html { render :edit, status: :unprocessable_entity, notice: 'Update failed!'}
          format.json { render :json => { :status => 'Error', :message => 'Error on update'}, :status => :unprocessable_entity }
        end
      end
    else
      render :show, status: :unauthorized, notice: 'Access unauthorized'
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.includes(:widgets).find(params[:id])
      @project.forum ||= Forum.new
      @project.save
      @forum = @project.forum
      #@project = current_user.projects.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.


    def project_params
      params.require(:project).permit!
    end
end

app/views/projects/_project.erb
  <tr data-href="<%= project_url(project) %>" data-toggle="slidePanel">
    <td class="pre-cell"></td>
    <td class="cell-60 responsive-hide">
        <%= link_to project, class: "avatar" do %>
        <% image_tag project.image.url(:thumb), class:"img-fluid" %>
        <% end %>
      </a>
    </td>
    <td>
      <div class="content">
        <div class="title">
          <%= link_to project.name, project %>
        </div>
        <div class="metas">
          <span class="description"><%= project.description %></span>

        </div>
      </div>
    </td>
    <td class="cell-150 forum-posts">

       <div class="rating rating-sm" data-score="4" data-plugin="rating"></div>
    </td>
    <td class="suf-cell"></td>
  </tr>

app/views/projects/_widget_forum.html.erb
<div class="grid-stack-item"
data-gs-x="0"
data-gs-y="6"
data-gs-width="12"
data-gs-height="5"
data-gs-no-resize=""
data-gs-no-move=""
data-gs-locked="">

<div class="grid-stack-item-content panel panel-bordered" >
  <div class="panel-heading">
    <h3 class="panel-title" >Fórum</h3>
    <div class="panel-actions">
    </div>
  </div>
  <div class="panel-body">
    <ul class="list-group list-group-full">
      <% @forum.topics.each  do |topic| %>
      <li class="list-group-item">
        <div class="media">
          <div class="media-left">

          </div>
          <div class="media-body">
            <%= link_to forum_topic_path(@forum, topic) do %>

            <h4 class="media-heading"><%= topic.title %></h4>
            <% end %>

            <small>Created by <%= topic.user.username %></small>

          </div>

          <div class="media-right">

          </div>
        </div>
      </li>

      <% end %>

    </ul>

    <%= link_to new_forum_topic_path(@project.forum) do %>
    <button class="btn btn-primary">

      <i class="icon wb-plus" aria-hidden="true"></i>
      Create topic
    </button>
    <% end %>

  </div>
</div>
</div>

app/views/projects/_widget_owner.html.erb
<div class="grid-stack-item"
data-gs-x="0"
data-gs-y="0"
data-gs-width="12"
data-gs-height="5"
data-gs-no-resize=""
data-gs-no-move=""
data-gs-locked="">

<div class="grid-stack-item-content panel panel-bordered" >
  <div class="panel-heading">
    <h3 class="panel-title" >Owners</h3>
    <div class="panel-actions">
    </div>
  </div>
  <div class="panel-body">
    <ul class="list-group list-group-full">
      <% @project.owners.each  do |member| %>
      <li class="list-group-item">
        <div class="media">
          <div class="media-left">
            <span class="avatar">
              <%= link_to user_path(member) do %>

              <img class="img-responsive" src="<%= member.avatar.url %>" alt="Photo of <%= member.name %>">
              <% end %>

            </span>
          </div>
          <div class="media-body">
            <%= link_to user_path(member) do %>

            <h4 class="media-heading"><%= member.name %></h4>
            <% end %>

            <small><%= t('Administrator')%></small>

          </div>

          <div class="media-right">
            <%= link_to '' ,project_user_path(@project, member),
            data: {:confirm => t('Are you sure?')}, :class => "status status-lg wb-close" , :method => :delete %>
          </div>
        </div>
      </li>

      <% end %>

    </ul>

    <%= link_to new_project_user_path(@project) do %>
    <button class="btn btn-primary">

      <i class="icon wb-plus" aria-hidden="true"></i>
      Add new administrator
    </button>
    <% end %>

  </div>
</div>
</div>

app/views/projects/edit.html.erb
<h1> <center> Editing <%= link_to @project.name, @project %> project</center ></h1>

<div class="container">
<div class="panel">
<div class="panel-body">
<div class="col-lg-3 profile-settings-sidebar">
	<h4>
	Public project logo
	</h4>
	<p>
	You can upload a logo of project here
	</p>
</div>

<div class="col-lg-9">
	<%= form_for @project, html: { multipart: true } do |f| %>

	<div class="clearfix avatar-image append-bottom-default">
	</div>
	<h5>
	Upload new project image
	</h5>
		<div id="container-upload" class='img-responsive <%= "hide" if @project.use_open_hub_image%>' style='width:350px;'>
			<%= f.file_field :image, data: {plugin: "dropify", "default-file": @project.image.url} %>
			<div class="help-block">
				max file size: 3MB
			</div>
		</div>
		<div id="container-openhub"  class='img-responsive <%= "hide" unless @project.use_open_hub_image%>' style='width:350px;'>
			<img src="<%= @project.open_hub_image_url %>"/>
		</div>
		<% if @project.use_open_hub_data %>
	<%= f.check_box :use_open_hub_image %> Use OpenHub image
<% end %>
	<br><br>

	<%= f.submit 'Change project logo', :class => 'btn btn-primary' %>

	<% end %>
</div>

</div>
</div>
<div class="panel">
	<%= form_for @project, html: { multipart: true } do |f| %>

<div class="panel-body">
<div class="row">
<div class="col-lg-3">
	<h4>
		Project information
	</h4>
	<p>
	Fill the project public informations here:
	</p>
</div>

<div class="col-lg-9">
	<div class="clearfix avatar-image append-bottom-default">

	</div>

	<div class="form-group">
    <h5>Project name</h5>
	    <%= f.text_field :name, :class => "form-control",
	    :placeholder => "Project name" %>
  	</div>

	<div class="form-group">
	    <h5>Project description</h5>
	    <%= f.text_area :description, :class => "form-control",
	    :placeholder => "Description"%>
  	</div>

	<div class="form-group">
	    <h5>Project page URL</h5>
	    <%= f.text_field :project_page_url, :class => "form-control",
	    :placeholder => 'http://'%>
  	</div>


  	<div class="form-group">
	  	<%= f.submit t('Submit'), :class => 'btn btn-primary' %>
  	</div>

</div>

</div>
</div>
<% end %>
</div>
</div>

app/views/projects/index.html.erb
<%= render 'visitor/header' unless current_user %>
<%= render 'visitor/menu' unless current_user %>

<div class="page-header text-center">
  <center>
    <%= image_tag "flosscoach-logo" %>
  </center>
  <h1 class="page-title ">  <%=t('Explore Flosscoach') %></h1>
  <p class="lead">
    <%=t('Discover projects, groups and technologies')%> <%=t('Share your projects with others')%>
  </p>
</div>
<!-- Panel -->
<div class="page-content">
  <div class="panel ">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @projects.count %> projects found</h3>
    </div>
    <div class="panel-body container-fluid">

      <div class="row row-lg">
        <div class="col-md-8">
          <form class="page-search-form" role="search">
            <div class="form-group">
              <div class="input-group">
                <%= form_tag projects_path, :method => 'get' do %>
                      <%= text_field_tag :search, params[:search], class: "form-control", placeholder:"Search..." %>
                      <span class="input-group-btn">
                      <%= submit_tag raw("Search"), style: "line-height:inherit;",
                      class: "btn btn-primary waves-effect waves-classic", data: { disable_with: "Please wait.." }%>
                    </span>

                  <% end %>


              </div>
              <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle btn-sm" id="searchFilter"
                data-toggle="dropdown" aria-expanded="false">
                Order by: <%= @order_by %>
              </button>
              <div class="dropdown-menu" aria-labelledby="searchFilter" role="menu">
                <%= link_to "Recents", recent_projects_path, class: "dropdown-item" %>
                <%= link_to "Most Favoritered", most_favorited_projects_path, class: "dropdown-item" %>
              </div>
            </div>
          </div>
        </form>


        <div class="page-content  page-content-table  ">
          <table class="table is-indent ">
            <table class="table is-indent">
              <tbody>
                <%= render @projects %>
              </tbody>
            </table>
          </div>

        </div>
        <div class="col-md-4">
          <div>
            <h4>Popular tags</h4>
            <div class="list-group list-group-bordered">
              <% Tag.all_ordered_by_count.first(10).each do |tag, count| %>
              <%= link_to "#{tag} - #{count} results", projects_path(search: tag), class:"list-group-item" %>

              <% end %>

            </div>
            <div>
              <% if current_user %>
              <div>
                <%= link_to "Create new project", new_project_path %>
              </div>
              <% end %>
            </div>
          </div>
        </div>

      </div>


    </div>
  </div>

</div>

app/views/projects/new.html.erb
<div class="page-header">

  <h1 class="page-title ">Create/add your project on FlossCoach</h1>
  <p class="lead">
    Add your project to FlossCoach and help newbies collaborate with your project.
  </p>
</div>

<div class="page-content">
  <div class="panel">
    <div class="panel-body container-fluid">
      <% if @project.errors.any? %>
      <div role="alert" class="alert dark alert-danger alert-icon alert-dismissible">
        <button aria-label="Close" data-dismiss="alert" class="close" type="button">
          <span aria-hidden="true">×</span>
        </button>
        <i class="icon md-notifications" aria-hidden="true"></i>
        <h4><%= pluralize(@project.errors.count, "Error") %> creating a project</h4>
        <ul>
          <% @project.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          <% @project.widgets.each do |widget| %>
            <% widget.errors.full_messages.each do |message| %>
              <li>Widget <%= message %></li>
            <% end %>
          <% end %>
        </ul>
      </div>
      <% end %>



  <%= form_for @project do |f| %>
  <div class="row">
    <div class="col-lg-12 form-group">
      <%= f.label :name, "Name" %>
      <%= f.text_field :name , :class => "form-control", placeholder: t('Name') %>
    </div>
    <div class="col-lg-12 form-group">
      <%= f.label :description, "Description" %>

      <%= f.text_area :description, :class => "form-control", :rows => 4, placeholder: t('Description') %>
    </div>
    <div class="col-lg-12 form-group">
      <%= check_box_tag 'openhub_check' %> <%=t('I want to get data from OpenHub')%>

    </div>
    <div class="col-lg-12 form-group">
      <%= f.label :tags, "Tags" %>
      <%= f.text_field :tags, class: "form-control" %>


    </div>

    <div class="col-sm-12 pull-right">
      <%= f.submit t('Create project') , class: "btn btn-primary btn-outline", data: { disable_with: "Please wait.." } %>

    </div>
    <% end %>
  </div>

  </div>

</div>

app/views/projects/show.html.erb
<%= render 'visitor/header' unless current_user %>
<%= render 'visitor/menu' unless current_user %>

<div id="<%= @project.id %>" class="page-header page-header-bordered page-header-tabs  nav-tabs-horizontal" data-plugin="tabs">

  <figure class='logo-projeto text-center'>
    <img class=" img-responsive" src="<%= @project.image.url %>"
    style="max-width:250px;"/>
  </figure>
  <h1 class="page-title text-center"><%= @project.name %>
    <% if @project.recent? %>
    <span class="badge badge-danger badge-sm">New</span>
    <% end %>
  </h1>
 
  <p class='text-center'><%= @project.description %></p>

  <div class="text-center">
    <small>Project created <%= time_ago_in_words @project.created_at %> ago</small>
  </div>
  <% unless @project.forum.nil? %>
  <div class="text-center">
    <%= link_to @project.forum, class: "btn btn-info waves-effect waves-classic" do %>

    <i class="icon md-comment" aria-hidden="true"></i>Visit the <%= @project.name%> forum!
    <% if @project.recent? %>
    <span class="badge badge-danger badge-sm">New</span>
    <% end %>
    <% end %>
  </div>
  <% end %>
  <ul class="nav nav-tabs" role="tablist">

    <%= tab_item(:about, "About", active: true ) %>
    <%= tab_item(:how_to_start, "How to start") %>
    <%= tab_item(:talk_to_the_community, "Talk to the community") %>
    <%= tab_item(:setup_your_workspace, "Setup your workspace") %>
    <%= tab_item(:deal_with_the_code, "Deal with the code") %>
    <%= tab_item(:submit_your_changes, "Submit your changes") %>
    <% if @project.owner?(current_user) %>
    <div class="dropdown float-right">
      <button type="button" class="float-right btn btn-primary dropdown-toggle float-right waves-effect waves-classic" id="exampleLeftDropdownSubMenu" aria-expanded="true" data-toggle="dropdown">
        Administration menu
      </button>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="exampleLeftDropdownSubMenu" role="menu">
        <%= link_to "Edit project", edit_project_path(@project), class: "dropdown-item" %>
        <a class="dropdown-item" href="javascript:void(0)" role="menuitem" tabindex="-1">Owners</a>
        <%= link_to "Create a forum","#", class: "dropdown-item" if @project.forum.nil?%>
      </div>
    </div>
    <% end %>
  </ul>

</div>
<div class="page-content container-fluid tab-content">
  <div class="tab-content pt-20">
    <% tab_pane(:about, active: true) do %>
    <%= render @project.widgets.from_tab(:about ) %>
    <% end %>
    <% tab_pane(:how_to_start, gridstack: false) do %>
    <div class="panel nav-tabs-horizontal" data-plugin="tabs">
      <div class="panel-heading">
        <h3 class="panel-title">How to start</h3>
      </div>
      <ul class="nav nav-tabs nav-tabs-line" role="tablist">
        <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#contribution_flow" role="tab">Contribution flow</a></li>
        <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#choosing_a_task_to_start_with" role="tab">Choosing a task to start with</a></li>
        <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#find_a_mentor" role="tab">Find a mentor</a></li>
      </ul>
      <div class="panel-body">
        <div class="tab-content">
          <div class="tab-pane active" id="contribution_flow" role="tabpanel">
            <p>Please consider following the flow below as it may help you in your first contribution. Tough following is not mandatory, it was tought to guide you as a begginer.
              You can move to appropriate guidelines and resources by clicking in the boxes
              instead of using the menu.</p>
              <%= render 'flow' %>
            </div>
            <% tab_pane(:choosing_a_task_to_start_with) do %>
            <%= render @project.widgets.from_tab(:choosing_a_task_to_start_with) %>
            <% end %>

            <% tab_pane(:find_a_mentor) do %>
            <%= render @project.widgets.from_tab(:find_a_mentor) %>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
      <% tab_pane(:talk_to_the_community, gridstack: false) do %>
      <div class="panel nav-tabs-horizontal" data-plugin="tabs">
        <div class="panel-heading">
          <h3 class="panel-title">Community support</h3>
        </div>
        <ul class="nav nav-tabs nav-tabs-line" role="tablist">
          <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#search_before_ask" role="tab">Search before ask</a></li>
          <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#synchronous_chat" role="tab">Synchronous chat</a></li>
          <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#mailing_lists" role="tab">Mailing lists</a></li>
        </ul>
        <div class="panel-body">
          <div class="tab-content">

            <% tab_pane(:search_before_ask, active: true) do %>
            <%= render @project.widgets.from_tab(:search_before_ask) %>
            <% end %>

            <% tab_pane(:synchronous_chat) do %>
            <%= render @project.widgets.from_tab(:synchronous_chat) %>
            <% end %>

            <% tab_pane(:mailing_lists) do %>
            <%= render @project.widgets.from_tab(:mailing_lists) %>
            <% end %>

          </div>
        </div>
      </div>
      <% end %>

      <% tab_pane(:setup_your_workspace) do %>
      <%= render @project.widgets.from_tab(:setup_your_workspace) %>
      <% end %>

      <% tab_pane(:deal_with_the_code) do %>
      <%= render @project.widgets.from_tab(:deal_with_the_code) %>

      <% end %>

      <% tab_pane(:submit_your_changes) do %>
      <%= render @project.widgets.from_tab(:submit_your_changes) %>
      <% end %>

    </div>


  </div>